version: '{build}'
image: Visual Studio 2015

platform: x64

environment:
  global:
    CONDA_NPY: "110"
    TRAVIS: "0"
    BOOST_DOWNLOAD_CACHE_DIR: "C:\\boost_cache"
    DISTUTILS_USE_SDK: 1
    MSSdk: 1

  matrix:
    - MINICONDA_PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      ARCH: "64"
      PYTHON_VERSION: 2.7

    - MINICONDA_PYTHON: "C:\\Miniconda35-x64"
      CONDA_PY: "35"
      ARCH: "64"
      PYTHON_VERSION: 3.5

install:
  - '%CMD_IN_ENV% "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x64'
  - "SET PATH=%MINICONDA_PYTHON%;%MINICONDA_PYTHON%\\Scripts;%PATH%;"
  - git submodule init
  - git submodule update
  - conda config --set always_yes true
  - conda update -q conda
  - conda install -q conda-build

build: false

test_script:
  - "%CMD_IN_ENV% conda build -q tools/conda-recipe"