trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

pr:
  - master

stages:
  - stage: Test
    jobs:
      - template: ./tools/ci/azure-pipelines/linux.yml
      - template: ./tools/ci/azure-pipelines/osx.yml
