run_parameters:
  flags:
    plot_results: true
    save_simularium: true
    save_vmd: false
    save_results: true
    enable_active_transport: true
    single_motor: false
    count_steps: true
    count_events: true
    enable_mitochondrial_dynamics: true
  io:
    outfile: "OUTFILE"
    outdir: "OUTDIR"
    model_file: "MODEL_FILE.pkl"

simulation:
  dt: 0.005 # s
  n_steps: 2.4e4 # 120s
  stride: 2.0e2 # 1 s
  temperature: 310.15 # K

units:
  length: um # micrometer
  time: s # second
  velocity: um/s
  diffusion: um^2/s
  force_constant_bond: kJ/mol/nm^2
  force_constant_angle: kJ/mol/rad^2
  angle: rad
  rate: 1/s # generic rate unit

motor:
  kinesin:
    binding_distance: 0.2 # um
    binding_rate: 3.75 # 1/s
    unbinding_rate: 1.27 # 1/s
    p_activate: 0.00030 # /dt
    p_active: 0.00030 # /dt
    deactivation_rate: 0.31 # 1/s
    velocity: 0.78 # um/s
    step_length: 0.05 # um
    polarity: 1 # dimensionless
    radius: 0.05 # um
    p_binding: 0.5 # dimensionless probability for creating a kinesin motor (vs dynein); must sum to 1.

  dynein:
    binding_distance: 0.2
    binding_rate: 3.75
    unbinding_rate: 0.44
    p_activate: 0.00030 # /dt
    p_active: 0.00030 # /dt
    deactivation_rate: 0.25
    velocity: 1.2
    step_length: 0.05
    polarity: -1
    radius: 0.05
    path_selection: random
    p_binding: 0.5 # dimensionless probability for creating a dynein motor (vs kinesin); must sum to 1.

mitochondria:
  radius: 0.15
  diffusion_constant: 0.005 # um^2/s
  kc_repulsion: 0.005 # kJ/mol/nm^2
  d_repulsion: 0.3
  kc_bond: 0.01
  eq_bond: 0.3
  kc_angle: 9.12 # kJ/mol/rad^2
  eq_angle: 3.1416
  fission_rate: 0.00044
  fusion_rate: 0.047 # control + noco30
  fusion_rate_noco60: 0.1 # noco60
  fusion_radius: 0.3
  enable_ss_fusion: false

tubulin:
  radius: 0.05
  diffusion_constant: 0.0178
  kc_repulsion: 0.005
  d_repulsion: 0.05
  kc_bond: 0.005
  eq_bond: 0.2
  kc_angle: 50.0
  eq_angle: 3.1416

nucleus:
  radius: 0.25

membrane:
  radius: 0.25

transport_parameters:
  bond_energy_threshold: 650.0
  rc_cleave_bond: 1.0e32
