name: readdy_ci

on: [push, pull_request]

jobs:
  readdy_ci:
    name: readdy_ci (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-10.15']
        python-version: ['3.7', '3.8', '3.9'] # used to build the conda package (not for miniconda installation)
    steps:
      - uses: actions/checkout@v2
      - if: github.repository == 'readdy/readdy' && github.event_name == 'push'
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: echo GITHUB_REF ${{github.ref}}
      - run: echo "$(git describe --always)"
      - run: echo "$(git tag)"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: prepare conda
        shell: bash -l {0}
        run: |
          conda config --set always_yes true
          conda config --add channels conda-forge
          conda config --set quiet true
          conda install conda-build conda-verify pip
      - name: build readdy conda package
        shell: bash -l {0}
        run: conda build tools/conda-recipe --python=${{ matrix.python-version }}
      - name: upload conda package
        shell: bash -l {0}
        # only upload conda package when origin and on pushes
        if: github.repository == 'readdy/readdy' && github.event_name == 'push'
        env:
          BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
          PYTHON_VERSION: ${{ matrix.python-version }}
        # if GITHUB_REF has tag then package is uploaded to normal anaconda channel
        # if GITHUB_REF points to master then package is uploaded to dev channel
        run: |
          tools/ci/github/upload_conda_package.sh
